apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: public-cluster
  region: us-west-2
  version: "1.29"  # Adjust as needed

vpc:
  subnets:
    public:
      us-west-2a:
        id: "subnet-xxxxxxx"
      us-west-2b:
        id: "subnet-yyyyyyy"
  clusterEndpoints:
    publicAccess: true
    privateAccess: false

nodeGroups:
  - name: ng-public
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
    ssh:
      allow: true
      publicKeyName: my-keypair
    associatePublicIp: true
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        ebs: true
        albIngress: true
    tags:
      nodegroup-role: public
      env: production
