name: Test 1 - Public Cluster Public Helm
on:
  push:
    branches:
      - main

jobs:
  basic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy to EKS
        uses: dinushchathurya/eks-helm-client-test@latest 
        env:
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
          REGION_CODE: ${{ secrets.REGION_CODE }}
        with:
          debug: true
          args:  >
            bash -c "
              helm repo add bitnami https://charts.bitnami.com/bitnami;
              helm repo update;
              helm install bitnami/mysql --generate-name -n test-basic --create-namespace;
              kubectl get pods -n test-basic
              kubectl get svc -n test-basic
            "