name: Deploy to EKS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    
    - name: Deploy with Helm to EKS
      uses: docker://dinushchathurya/eks-helm-client-test:latest
      env:
        REGION_CODE: ${{ secrets.REGION_CODE }}
        CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
        HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
        HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
      with:
        args: |
          helm registry login demo.goharbor.io --username $HARBOR_USERNAME --password $HARBOR_PASSWORD
          helm uninstall mysql-release -n test-basic || true
          helm install mysql-release oci://demo.goharbor.io/devninja/mysql --version 13.0.2 -n test-basic --create-namespace
          kubectl get pods -n test-basic
          kubectl get svc -n test-basic