name: Deploy to Private Helm to Public Cluster

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/2-public-cluster-private-helm.yaml'

jobs:
  basic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy to EKS
        uses: docker://dinushchathurya/eks-helm-client-test:latest 
        env:
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
          REGION_CODE: ${{ secrets.REGION_CODE }}
          HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
          HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
        with:
          args: | 
            helm repo add bitnami https://charts.bitnami.com/bitnami
            helm repo update
            helm install bitnami/mysql --generate-name -n test-basic-public --create-namespace
            kubectl get pods -n test-basic-public
            kubectl get svc -n test-basic-public
            kubectl delete -n test-basic-public --all || true


            